import { EContentTypes } from "../types";
import { SfItemProps } from "./sf-item";

export const storefrontList: Array<SfItemProps> = [
  {
    name: "Summertime Favorites",
    slug: "summertime-favorites",
    contents: [
      {
        type: EContentTypes.SocialContent,
        contentUrl: "/videos/tiktok_prod_1.mp4",
        platform: "tik-tok",
        thumbnailUrl: "/images/thumbnail_tiktok_1.png",
        id: "video",
        name: "The Hair Oil",
        products: [],
      },
      {
        id: "1",
        type: EContentTypes.Product,
        name: "The Hair Oil",
        category: "Crown Affair",
        description:
          "A lightweight, five-ingredient hair oil for all hair types that provides deep hydration...",
        imageUrl: "/images/prod_1.png",
        url: "http://localhost:3000/products/1",
        nearestAvailableStore: "Sephora",
      },
      {
        id: "2",
        type: EContentTypes.Product,
        name: "Soft Pinch Luminous Powder Blush",
        category: "Rare Beauty by Selena Gomez",
        description: "A lightweight glowy blush with buildable, seamle",
        imageUrl: "/images/prod_2.png",
        url: "http://localhost:3000/products/2",
      },
      {
        id: "3",
        type: EContentTypes.Product,
        name: "Soft Pinch Liquid Blush",
        category: "Rare Beauty by Selena Gomez",
        description: "A weightless, long-lasting liquid blush that blends...",
        imageUrl: "/images/prod_3.png",
        url: "http://localhost:3000/products/3",
        nearestAvailableStore: "Sephora",
      },
      {
        id: "4",
        type: EContentTypes.Product,
        name: "Cookie and Tickle Powder Highlighters",
        category: "Benefit Cosmetics",
        description: "An innovative powder highlighter that gives skin....",
        imageUrl: "/images/prod_4.png",
        url: "http://localhost:3000/products/4",
      },
      {
        id: "5",
        type: EContentTypes.Product,
        name: "Beijos del Sol Perfume Mist",
        category: "Sol de Janeiro",
        description: "Peach Skin, Coconut Milk, Frangipani Petals",
        imageUrl: "/images/prod_5.png",
        url: "http://localhost:3000/products/5",
        nearestAvailableStore: "Sephora",
      },
      {
        id: "6",
        type: EContentTypes.Product,
        name: "Honey Infused Hydrating Lip Oil",
        category: "Gisou",
        description: "A lip oil powered by Mirsalehi honey and bee garden...",
        imageUrl: "/images/prod_6.png",
        url: "http://localhost:3000/products/6",
      },
      {
        id: "1",
        type: EContentTypes.Product,
        name: "Lip Glowy Balm",
        category: "LANEIGE",
        description: "A lightweight, moisture-rich lip balm with shea and ...",
        imageUrl: "/images/prod_7.png",
        url: "http://localhost:3000/products/7",
        nearestAvailableStore: "Sephora",
      },
    ],
  },
  {
    name: "Ultimate Glowing Skin Tutorial",
    slug: "ultimate-glowing-skin-tutorial",
    contents: [
      {
        type: EContentTypes.SocialContent,
        contentUrl: "/videos/tiktok_prod_2.mp4",
        platform: "tik-tok",
        thumbnailUrl: "/images/thumbnail_tiktok_1.png",
        id: "video_tiktok_2",
        name: "The Hair Oil",
        products: [],
      },
      {
        id: "8",
        type: EContentTypes.Product,
        name: "Watermelon Glow PHA + BHA Pore-Tight Toner",
        category: "Glow Recipe",
        description: "A super creamy, do-it-all eyeshadow stick that makes...",
        imageUrl: "/images/prod_8.png",
        url: "http://localhost:3000/products/9",
        nearestAvailableStore: "Sephora",
      },
      {
        id: "9",
        type: EContentTypes.Product,
        name: "Positive Light Silky Touch Highlighter",
        category: "Rare Beauty by Selena Gomez",
        description:
          "An innovative powder highlighter that gives skin an instant glass-like sheen for...",
        imageUrl: "/images/prod_9.png",
        url: "http://localhost:3000/products/9",
        nearestAvailableStore: "Sephora",
      },
      {
        id: "10",
        type: EContentTypes.Product,
        name: "All of the Above Weightless Eyeshadow",
        category: "Rare Beauty by Selena Gomez",
        description: "A super creamy, do-it-all eyeshadow stick that makes...",
        imageUrl: "/images/prod_10.png",
        url: "http://localhost:3000/products/10",
        nearestAvailableStore: "Sephora",
      },
      {
        id: "11",
        type: EContentTypes.Product,
        name: "Balm Dotcom Lip Balm and Skin Salve",
        category: "Glossier",
        description:
          "An innovative powder highlighter that gives skin an instant glass-like sheen for...",
        imageUrl: "/images/prod_11.png",
        url: "http://localhost:3000/products/11",
        nearestAvailableStore: "Sephora",
      },
      {
        id: "12",
        type: EContentTypes.Product,
        name: "Velour Makeup Powder Puff",
        category: "SEPHORA COLLECTION",
        description:
          "A velour triangular makeup puff for precise, flawless application of face powders.",
        imageUrl: "/images/prod_12.png",
        url: "http://localhost:3000/products/12",
        nearestAvailableStore: "Sephora",
      },
    ],
  },
];
